// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "pic",
    columns: [
      { name: "caption", type: "string" },
      { name: "url", type: "string", unique: true },
      { name: "aspect_ratio", type: "float" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Pic = InferredTypes["pic"];
export type PicRecord = Pic & XataRecord;

export type DatabaseSchema = {
  pic: PicRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://greatpics-4n9d0o.us-east-1.xata.sh/db/app",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
